### ISSUE TITLE
latest CAVA release is not installing gives undefined symbol error 

### ISSUE THREAD

**Issue by swatibodh** [RahmanTeam/CAVA#13]
/CAVA-1.2.3$ cava -c config.txt -i /home/swati/snpEff_latest_core/snpEff/glioma2/GRCh37/bow_gatk.vcf -o bow_gatk_cava
/home/swati/.local/bin/cava: line 4: /home/swati/.local/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/home/swati/.local/bin/CAVA.py", line 4, in <module>
    from cava_ import main
  File "/home/swati/.local/lib/python2.7/site-packages/cava_/main.py", line 10, in <module>
    import pysam
  File "/home/swati/.local/lib/python2.7/site-packages/pysam/__init__.py", line 1, in <module>
    from pysam.csamtools import *
ImportError: /home/swati/.local/lib/python2.7/site-packages/pysam/csamtools.so: undefined symbol: update_posmap

**Comment by vishramt7** [comment]
Hi, 
  I am facing the same issue on our Ubuntu20.04 server. Were you able to fix it ?
Thanks,
Vishram

**Comment by JeffreyMaurer** [comment]
I hit a similar error when running `get_refmeta` from the modtools python package when our Ubuntu server had pysam 0.7.6 and 0.7.7 for python 2.7

Running `sudo easy_install pysam==0.20.0` resolved this specific issue:

> from pysam.csamtools import *
> ImportError: /home/USER/.local/lib/python2.7/site-packages/pysam/csamtools.so: undefined symbol: update_posmap

My assumption is that it's because it's the first "static inline" function the linker gets to and old pysams have incompatible flags? Not an expert, but it's the only function in that particular file that has "static inline" modifier.
