### ISSUE TITLE
Installation error : SSL required

### ISSUE THREAD

**Issue by vigneshravi** [RahmanTeam/CAVA#6]
When I try to install v1.2.0 and v1.2.3 using "./install.sh" , I enounter the following error. Any help in fixing this is much appreciated, thanks!

Traceback (most recent call last):
  File "setup.py", line 130, in <module>
    get_setuptools.run()
  File "/opt/FlaskApp/appCGRL/static/CommonAnnotators/CAVAv1.2.0/CAVA-master/pysam-0.7.7/get_setuptools.py", line 89, in run
    return download()
  File "/opt/FlaskApp/appCGRL/static/CommonAnnotators/CAVAv1.2.0/CAVA-master/pysam-0.7.7/get_setuptools.py", line 66, in download
    egg = download_setuptools()
  File "/opt/FlaskApp/appCGRL/static/CommonAnnotators/CAVAv1.2.0/CAVA-master/pysam-0.7.7/get_setuptools.py", line 79, in download_setuptools
    src = urllib2.urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required

**Comment by marton-munz** [comment]
Hi Vignesh,
As for v1.2.0, we are aware of this installation error caused by an update in the Python Package Index. That is why we released v1.2.3 in which the issue you described is believed to be fixed, please see:
https://groups.google.com/forum/#!topic/cava-user-group/sOBgBjApqWE
Could you please double check if you get the same error when installing v1.2.3? Let me know if it works or you still encounter that error.
Thanks,
Márton

**Comment by JoshuaMichaelHanson** [comment]
Can confirm still an issue with osX Sierra Version 10.12.6
Replace this line in the setup.sh and should work
#pip install --no-cache-dir --ignore-installed --force-reinstall --upgrade pip
curl https://bootstrap.pypa.io/get-pip.py | python
